### ISSUE TITLE
Lesson total off by one (after #9 recently added)

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#104]
Maybe this is premature and lesson 9 shouldn't actually be available yet (?), but I was able to see it and then I noticed a few quantity-oriented things:

- The "Our Courses" page shows that "Intro to Vue.js" has 8 lessons.
- My dashboard shows "9 / 8 lessons completed".
- Lesson 8's "Next lesson" button is disabled, and doesn't allow going forward to lesson #9.

**Comment by pieer** [comment]
Thanks. This is fixed now
