### ISSUE TITLE
Lesson 10 radio button formatting

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#106]
This is a visual idea to reset some CSS that makes the radio buttons a little bit "off", but in no way is needed for the lesson.

The radio buttons are formatted oddly, due to the input styling in the CSS panel of the codepen. The current styling covers all HTML input components, including the radio buttons asked for in the challenge. It looks awkward because of the set height and width, making the radio buttons large-ish and centered and out of alignment with the labels.

As a suggestion, add CSS for the radio buttons that resets their height and width. Maybe something similar to:

input[type="radio"] {
  height: auto;
  width: auto;
}

**Comment by Gregg** [comment]
@atomjar please respond when you have a moment =)

**Comment by pieer** [comment]
@atomjar can we close this issue?

**Comment by atomjar** [comment]
Yes @pieer thanks
