### ISSUE TITLE
Add Upcoming Lessons - Static

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#117]
On the courses page between the course listing and VueConf, we need to display the lesson release schedule.  

<img width="478" alt="release schedule" src="https://user-images.githubusercontent.com/2618/39272565-3c42537e-48aa-11e8-8212-137718401862.png">

It'll start with this data:

May 8, 2018 | Advanced Components | Reactivity in Vue.js
May 15, 2018 | Advanced Components | Template Compilation
May 22, 2018 | Advanced Components | Functional Components
May 29, 2018 | Advanced Components | Mounting Process
June 5, 2018 | Intro to Vue.js | Tabs
June 12, 2018 | Advanced Components | Render Props & Scoped Slots

I'm very unsure of the best way to display this.  Likely the lesson names should be the highest priority, "To be released on: " the second, and the course is the third.

@whosdustin I'm sorry I don't have more ideas on how to display this data, I'm hoping you can mock something up in the morning.  Or even build staticly in staging, and Pierre can add the dynamic functionality later next week after we launch, since we can just launch with what is listed above.

**Comment by whosdustin** [comment]
I have a brief suggestion since this page is full of course information. What if we display the upcoming lessons inside the corresponding courses card?

Then under the actual course list, we can display upcoming courses if they have not been added. This is a very rough idea but I wanted to run it by you to see how you feel.

![card - course soon copy](https://user-images.githubusercontent.com/940208/39305647-036caf70-4988-11e8-8bbd-490298016b40.jpg)

**Comment by Gregg** [comment]
Yes, sounds good Dustin.  We'd like to also add an icon... Maybe the same calendar icon we use in the lessons next to the title:

![image](https://user-images.githubusercontent.com/2618/39325099-565fbe30-495f-11e8-85f5-4a5b15fa7c94.png)

**Comment by whosdustin** [comment]
Pushed static code up to payment branch. Added TODOs to help @pieer with the functionality. 

Also, wanted to ask @Gregg do we want these upcoming lessons to display in just the courses page? These cards are on the homepage and on the dashboard. We could have the upcoming display everywhere or just keep it on the courses page.

**Comment by pieer** [comment]
Done. @Gregg do you want this only on courses page or globaly?

**Comment by Gregg** [comment]
Just on the courses page for now.  Thanks!

**Comment by Gregg** [comment]
I think this is done for the most part.  Closing out.
