### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by max-devjs** [Code-Pop/vue-mastery#12]
Forms accept not valid tld, notably:

```
mysite123@gmail.b
mysite123@gmail.bewqeqwewqeqw
```

Also, a few malformed addresses are accepted as valid.

accepted
```
mysite@.com.my
@you.me.net
mysite123@gmail.b
mysite@.org.org
.mysite@mysite.org
mysite()*@gmail.com
```
not accepted
```
mysite.ourearth.com
```

**Comment by pieer** [comment]
Thanks max. Yes we are very permissive at the moment. I'm going to add more validation here.
