### ISSUE TITLE
Add checkoutinfo to API call for Abandoned Cart Info

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#123]
I just wrote up an abandoned cart email, which in chargebee I can send to anyone who looks at the payment options (clicks on a button on the pricing page) but doesn't convert after 30 minutes.  Looks like this:

![image](https://user-images.githubusercontent.com/2618/39379957-e65008ee-4a2a-11e8-8b72-5c5011ff133f.png)

In order to get this to work we need to send additional data into the API call which includes "checkout_info"  See here: https://www.chargebee.com/docs/abandoned-carts.html

Also, here's the property: https://apidocs.chargebee.com/docs/api/hosted_pages#hosted_page_checkout_info

This is lower priority than team accounts.

**Comment by pieer** [comment]
Email, first name and last name are now populated into chargebee on checkout. I'm using the display name and split it when possible.
