### ISSUE TITLE
Upcoming courses / lessons bugs

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#124]
- [ ] First up "Upcoming courses" should read "Upcoming lessons"

![can i update this -1-1](https://user-images.githubusercontent.com/2618/39380375-56bd91f4-4a2c-11e8-8638-552a6bb6e528.jpg)

- [ ] Also, one of the lessons I added should be listed under "Intro to Vue.js".

![vue mastery course listing](https://user-images.githubusercontent.com/2618/39380442-94621066-4a2c-11e8-92cb-d85c24ac6898.jpg)

In flamelink it is indeed listed under the proper course:

![edit content _ lessons _ tabs - flamelink](https://user-images.githubusercontent.com/2618/39380476-b1911efc-4a2c-11e8-9e5c-d690165a9aed.jpg)

So why is it listed in the wrong place?  Also noticed that Tabs is being listed as a lesson under Advanced Components INSIDE the course.. on the lessons listing.
 
- [ ] The wrong number of lessons is listed on the course listing page.  Only non-draft lessons should count towards the total

![vue mastery course listing-1](https://user-images.githubusercontent.com/2618/39380656-547968fe-4a2d-11e8-9ead-0efd4baf6412.jpg)

Please note that the number of lessons is also displayed on the dashboard, under "Progress" and "Recommended Courses"

**Comment by pieer** [comment]
Fixed
