### ISSUE TITLE
Add Free Course & Free Lesson Label

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#126]
Hey @whosdustin this was listed in another ticket, but I fear it may be glossed over.

Courses & lessons that are free should have a label which shows they are free.   Could be a tag of some sort, or a wrap.  I'll leave it to you.

On the /courses page:
![vue mastery course listing-2](https://user-images.githubusercontent.com/2618/39381182-4192b978-4a2f-11e8-90c6-90c58698bff2.jpg)

On the front page:
![skitched-20180427-152636](https://user-images.githubusercontent.com/2618/39381207-60953288-4a2f-11e8-8bcc-c73709fd24ff.jpg)

On the dashboard: 
![asdf](https://user-images.githubusercontent.com/2618/39381290-9c30a96c-4a2f-11e8-94bd-5d1274f0ce2b.jpg)

Also, @pieer I'm hoping that these free tags can NOT be displayed if the user has a paid subscription.  No worries on the staticly generated pages though.

**Comment by whosdustin** [comment]
I just wanted to bring this up as a thought. We currently don't have a switch on Courses that tells me that the entire course is free. We only have a switch determining whether the lesson is free.

If a course contains a free lesson does that mean the entire course is free? Or will we be having a course with free lessons inside along with some more experienced lessons paid for? If that's the case is the course truly free?

If that will never happen then I will check if a course contains a free lesson and add the "Free" badge to it

**Comment by Gregg** [comment]
If a course is marked as free, that means all the lessons inside of it are free.  I suspect @pieer will need to add a flag for this on courses.  Yeah?

**Comment by Gregg** [comment]
Hey @whosdustin , when I look at the code referenced here, it doesn't seem like this is implemented as needed.  

I need to be able to toggle whether or not a course has a free tag (will need your help with this Pierre).. AND I need to be able to toggle if a lesson is free (or not).  

Please take a close look at the screenshots above and let me know if this is all ready to go for @pieer to do his part.

**Comment by whosdustin** [comment]
I just referenced the missing commits to this issue. 

As of right now, _Lessons_ you already have the ability to mark free or not. That functionality has already been connected in commit `a955904`. So if a lesson is marked free then the label shows up. 

For _Courses_ we spoke earlier and came up with marking All courses free until a later date, in which @pieer would offer the same _free_ toggle switch in Flamelink, similar to that in Lessons. Then we can add the toggle view in `courses/lists.vue` component on line 9.

**Comment by pieer** [comment]
Done
