### ISSUE TITLE
Add Subscribe button to homepage

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#127]
Adam and I just realized that there needs to be a "Subscribe" button on the homepage that links to the pricing page.  Using DevTools we mocked something like this up, where the Subscribe button is more primary than the View Courses button.  @whosdustin leaving it to you to mess with the color.  FYI, we didn't like that button transparent, or solid white.

![skitched-20180427-173849](https://user-images.githubusercontent.com/2618/39386273-d8bc6ee0-4a41-11e8-916e-0a90bb6e0f8d.jpg)

**Comment by whosdustin** [comment]
LOL that doesn't really leave me with any room to 'mess around'. I'll just do what you guys made to not upset any parties.

**Comment by Gregg** [comment]
Feel free to create another design for this @whosdustin ... Closing out because what you have works for now.
