### ISSUE TITLE
Mobile nav bar cut off

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#128]
Here's how the Vue Mastery Nav bar looks on my phone, when you click the two lines from the homepage.  Is that blue line suposed to be there?

![img_06d8bc954869-1](https://user-images.githubusercontent.com/2618/39386438-a20fe3ee-4a42-11e8-8d18-3c82c2acc3ea.jpg)

**Comment by whosdustin** [comment]
This has been resolved in my recent commit to fix #130
