### ISSUE TITLE
Login modal not mobile friendly

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#129]
When I login the modal that pops up doesn't look great on Mobile.  Here's how it looks on my phone.  Probably need to rethink the UI?

![img_7e555e1d4b66-1](https://user-images.githubusercontent.com/2618/39386489-dc995748-4a42-11e8-8ba3-8e6a36d7005e.jpeg)

**Comment by pieer** [comment]
Ok, I'll work on it

**Comment by pieer** [comment]
This is fixed now
