### ISSUE TITLE
"I accept the terms and conditions" link

### ISSUE THREAD

**Issue by max-devjs** [Code-Pop/vue-mastery#13]
- hardly noticeable as a link.
- clicking "I accept the " switches the checkbox (not opening "Terms of Service" page)

**Comment by pieer** [comment]
Thanks for your feed back Max. 
You're right, we should have different color. 

@whosdustin what color do you reckon?
@Gregg I've added the link yesterday, do you confirm we have to?

**Comment by pieer** [comment]
I've added the color in the link
