### ISSUE TITLE
Thank you page not mobile friendly

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#130]
When I view the thank you page on my mobile device it's weirdly not centered, and when I scroll down the bottom of the page looks cut off.

![img_0ad0ebc90bd8-1-1](https://user-images.githubusercontent.com/2618/39386667-b3a44b8a-4a43-11e8-8838-e4c2192b1e11.jpg)

![img_905a09505723-1](https://user-images.githubusercontent.com/2618/39386697-ce037cbc-4a43-11e8-8fe6-4658ec59d3c5.jpg)

**Comment by Gregg** [comment]
Also, when I open the menu from this page, here's what I see:

![img_c52f1740e480-1](https://user-images.githubusercontent.com/2618/39386812-60166e20-4a44-11e8-9236-cda130cced10.jpg)

**Comment by whosdustin** [comment]
All items here should be fixed.
