### ISSUE TITLE
Subscription "signup to payment" process doesn't quite work on mobile

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#131]
When trying to signup on my iphone, after I create my account, the payment modal / window is not called up after I create my account. I have to hit the plan again.  

Notice it pops up the payment modal in an entirely new window!  I wasn't expecting that to happen.  I mean, it's fine, it'd just be nice if it worked properly.  

See this video:
https://www.dropbox.com/s/g4cqp4amsskhspe/ScreenRecording_04-27-2018%2018-13-54.MP4?dl=0

**Comment by Gregg** [comment]
Just to document, we discussed having a workaround where if a user is on mobile, after they login they're shown a modal that has a single button that says "Click here to Susbcribe" ... This button would then lead them to the correct pricing modal they clicked on originally.  

We're doing this because it seems like we need a click to open a new window on mobile.

**Comment by Gregg** [comment]
This is not working for me.  See this screencast.  I was not logged in, I hit the monthly payments, filled the signup form.  I see four issues, and one stretch goal.

- [ ] The "You are now logged in modal" should not appear, only the "Click Here to Subscribe"
- [ ] The "Click Here to Subscribe" modal should not fade away after 3 seconds.  I often missed it.
- [ ] Clicking the "click here to subscribe" link causes the modal to continuously pop up.
- [ ] Clicking the actual "Select Plan" button also just causes the modal to pop up.  
- [ ] Stretch goal (optional): Make the "Click here to subscribe" a sexy green button.

https://www.dropbox.com/s/q7yupantkn6rckm/ScreenRecording_05-11-2018%2014-23-24.MP4?dl=0

**Comment by Gregg** [comment]
When I'm on desktop and I click "Select Plan" and create an account, I see the background modals.  Can you not show these if the payment modal worked?  If this isn't easy, don't sweat it.  

![vuemastery](https://user-images.githubusercontent.com/2618/39941202-c7a75514-5529-11e8-9d12-3d1b22128404.jpg)

**Comment by pieer** [comment]
@whosdustin I leave it to you to style the button
