### ISSUE TITLE
End of paid video goes to blank page

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#132]
When you reach the end of "Build a Reactivity" system:

https://vue-mastery-staging.firebaseapp.com/courses/advanced-components/build-a-reactivity-system

The modal for advancing to the next video pops up, and you are advanced to the next video which is empty (and a draft).  If the next video is a draft it should behave the same way it does when there is no video.  There should be no pop-up.

**Comment by pieer** [comment]
This should be fixed however I can't test because the video is not whitelisted on staging

**Comment by pieer** [comment]
I've tested it with another course and it works now
