### ISSUE TITLE
Copy suggestions for payments process

### ISSUE THREAD

**Issue by nilstaranger** [Code-Pop/vue-mastery#133]
I just went through the payment process and have a few suggestions for the copy.

1. On the pricing page, I see “guaranteed value” for monthly and annual plans. As a new user, I don’t know what this means but I feel a slight gimmicky sense. Consider removing?

2. On the pricing page, I see “Team” and immediately thought it was the vue mastery team ready to help me with questions about the two plans above. I think it should say “Team accounts” and the copy should say something like “Reach out for special annual pricing for your team”

3. On the Thank You page, under “Our Content” it reads “We’ll be releasing content weekly.” I think it should say “We release content weekly.” Change “what’s upcoming” to “what is coming up”. Under “Your Feedback”, change “request any content” to “have suggestions for future content”
Change hyperlink on “contact” to “contact us” or delete it altogether.

5. In the “A Free Gift from Vue Mastery” email, it says:
"Thank you for signing up with Vue Mastery," change to: “Thank you for signing up with Vue Mastery!"
Second paragraph, “As” is in italics, it should be normal.
Change Gregg Pollack to “-Gregg Pollack” or “Thanks again for joining,
Gregg Pollack”

6. In the “Expressing gratitude” email,
Add comma: To be honest with you [add comma] it's super

Change: "As you've probably noticed by now, about 25% of your monthly or annual subscription we send directly to the Vue.js project."
To:
"As you've probably noticed by now, we send about 25% of your monthly or annual subscription directly to the Vue.js project."

Add "the": where we publish [the] latest news

Consider changing: “To be honest with you it's super scary to try to make a living teaching.  That's why it means so much to me that you've chosen Vue Mastery as a learning resource.” I would be more interested in hearing something like “I’ve devoted my career to teaching disruptive technologies that have the potential to make the world a better place. Thats why it means so much to me…”

7. In “Your subscription has expired” email
Add ! To this sentence: We're sorry to see you go [!]

**Comment by Gregg** [comment]
1. Changing this in #167
2. Changing in #167
3. Changed.
4. Done.
5. Done.
7. Done.

Thank you for all your help!
