### ISSUE TITLE
Too much white space left of Team box

### ISSUE THREAD

**Issue by ChaseWGregory** [Code-Pop/vue-mastery#134]
<img width="1154" alt="screen shot 2018-04-30 at 5 01 09 pm" src="https://user-images.githubusercontent.com/35742533/39450239-a22c6cf0-4c98-11e8-8ce0-293a1c735c97.png">

**Comment by ChaseWGregory** [comment]
Same issue with Thank You page on Desktop and Mobile
<img width="1161" alt="screen shot 2018-04-30 at 5 23 26 pm" src="https://user-images.githubusercontent.com/35742533/39451020-40a5aa3e-4c9b-11e8-956e-e1e5e0954ebe.png">

On Mobile Chrome iPhone 7+
Should be centered?
![img_6537](https://user-images.githubusercontent.com/35742533/39451030-4950dfd2-4c9b-11e8-81d4-342161a55dc4.PNG)

**Comment by Gregg** [comment]
Thanks for your feedback here, but the whole space is there to make things feel less crowded.  And if you expand your browser a little more on the pricing page, you’ll see the team become a column.  

Closing for now, but we will see if others comment on this.
