### ISSUE TITLE
Paypal pop-up shows sandbox 

### ISSUE THREAD

**Issue by ChaseWGregory** [Code-Pop/vue-mastery#135]
I requested to sign up for a monthly and pay with paypal, This is where I got stuck. 
<img width="1245" alt="screen shot 2018-04-30 at 5 07 29 pm" src="https://user-images.githubusercontent.com/35742533/39450494-83228104-4c99-11e8-8d6d-52160d0c5552.png">

**Comment by Gregg** [comment]
It should be the sandbox, we are testing there.  Are you saying nothing showed?  If yes, maybe try again.

**Comment by Gregg** [comment]
Closing for now.. please re-open if you can duplicate.
