### ISSUE TITLE
Google Signin

### ISSUE THREAD

**Issue by atomjar** [Code-Pop/vue-mastery#136]
When I click on "Select Plan", then click "Google" on the modal that pops up, I just get this:
Please read and accept the terms and conditions

It doesn't seem to be activating the Google authentication. Same goes for Github button.

**Comment by Gregg** [comment]
I’m unsure Google or Github signup is supposed to work on Staging.

**Comment by Gregg** [comment]
Closing out this ticket for now, will test again when we have pricing back up on Staging Wednesday.
