### ISSUE TITLE
Advance Components routing bug

### ISSUE THREAD

**Issue by atomjar** [Code-Pop/vue-mastery#138]
From my dashboard, when I click "Resume" on the Advanced Components course, it takes me to a broken page that looks like:
<img width="1650" alt="screen shot 2018-04-30 at 5 35 00 pm" src="https://user-images.githubusercontent.com/23220360/39451542-f83e37fa-4c9c-11e8-8615-2045d9b17405.png">

**Comment by Gregg** [comment]
It's trying to bring you to a page that does not exist, a draft lesson.

**Comment by pieer** [comment]
This is fixed
