### ISSUE TITLE
Thank you page needs a capital D and a link in Subscription section

### ISSUE THREAD

**Issue by ChaseWGregory** [Code-Pop/vue-mastery#140]
"dashboard" should be a button and needs a Capital "D" as it shows in the main menu.

<img width="468" alt="screen shot 2018-04-30 at 5 31 49 pm" src="https://user-images.githubusercontent.com/35742533/39451387-850f45c6-4c9c-11e8-91a9-0a8717c40648.png">

**Comment by whosdustin** [comment]
This has been fixed in my recent commit.
