### ISSUE TITLE
Confusion while paying with PayPal

### ISSUE THREAD

**Issue by atomjar** [Code-Pop/vue-mastery#143]
After being redirected to PayPal, and clicking "Agree and continue" on the window it directs you to, it's unclear what the next step is. I guessed that I should click "Pay and continue" on the Chargebee modal, but that was just a guess, and didn't seem clear.

**Comment by Gregg** [comment]
Are you saying after you pay with PayPal?  

I know the modal changes so you can submit payment.  Screenshot?

**Comment by Gregg** [comment]
We changed the button you're brought back to .. to be "Activate My Subscription"
