### ISSUE TITLE
Intro video's audio

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#145]
In the current production site, https://www.vuemastery.com/, the video's audio has Adam on the right side and Adam on the left. If this is a kind of audio "branding" that you want in your videos, you might want to consider applying the same style to the into video at https://vue-mastery-staging.firebaseapp.com/, where the voice-over audio is centered.

In the https://vue-mastery-staging.firebaseapp.com/ intro video, the audio level is on the low side and I kept wanting to turn it up more.

**Comment by Gregg** [comment]
Let me know what you think @atomjar

**Comment by Gregg** [comment]
Following up.  Thoughts @atomjar ?

**Comment by atomjar** [comment]
Good ear for detail @somascope! I made the choice to keep our audio centered in this version as I felt it sounded a bit smoother. Thanks for all of your feedback!
