### ISSUE TITLE
New user sign up confusion

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#146]
https://vue-mastery-staging.firebaseapp.com/

I wonder if this issue might be due to me not (yet) trying a subscription/paid plan... As a hypothetical new user, I went ahead with signing up and presumed I'd be able to see (some of) the lessons...

1. I pressed Sign Up and created a new account in the modal window, where this window closes when you have signed up.
2. On the main page under "Latest Lessons", I navigated to Forms to see a lesson.
3. Arriving on the Forms lesson, I saw the "This Lesson Is Locked. Create a free account to unlock it." message covering the video area with the green "Unlock Content" button.

I did pursue using the "I already have an account" option after pressing the "Unlock Content" button, but this still didn't git rid of the locked message.

This confused me since I had just created an account and expected to not be shown such a message.

Is all content eventually going to be behind the paywall? I wasn't sure what (if anything) might be free and what might be paid/premium content at this point.

**Comment by somascope** [comment]
Looking more at the site, I'd call this a "sign up" versus "subscribe" confusion issue.

**Comment by Gregg** [comment]
Thanks for testing.  I wonder if you weren’t actually logged in when on step 1?   Because you should have been able to see the form video automatically when you logged in..  could you please verify?

**Comment by somascope** [comment]
I had tried this before I'd created a new account so I was not yet logged in. However, I found that the issue was more connected to which lesson I was viewing, Lesson 10 (Forms). That lesson appears to be a locked lesson. Since it was the top-most item under Latest Lessons, I clicked on it and was then confused why it wasn't available. I'm still not sure why, but maybe these included screen grabs can show this and give you more info.

![grab1](https://user-images.githubusercontent.com/8138678/39477400-d475979a-4d24-11e8-8903-ada8f7a5477b.png)

![grab2](https://user-images.githubusercontent.com/8138678/39477415-dbc05af8-4d24-11e8-92b3-c69755e4da00.png)

![grab3](https://user-images.githubusercontent.com/8138678/39477423-e3dba56c-4d24-11e8-953f-91c36890f538.png)

**Comment by Gregg** [comment]
You're totally right!  Something stopped working.  

@pieer .. The lesson state where you can watch a (locked) video if you have a free account stopped working.  See https://vue-mastery-staging.firebaseapp.com/courses/intro-to-vue-js/forms  This should be viewable if you have a free account, but it's not.

**Comment by pieer** [comment]
I did find this bug and corrected it this morning. Now on staging.
