### ISSUE TITLE
Text edits on subscription thank you page

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#147]
In the top "You are supporting Open Source!" section, I'm not sure what your capitalization style guie is, but this seems inconsistent with "supporting" not being capitalized.

In the "Your Subscription" section, the first paragraph is missing a period: Your subscription will automatically renew on May 30, 2018

At the end of the "Your Feedback" section, the last sentence is missing a period: You can use the contact us form or just email team@vuemastery.com

**Comment by somascope** [comment]
In the "Your Feedback" section, there's a space missing between "us" and "form": "You can use the contact usform..."

**Comment by Gregg** [comment]
We all seem to need a lesson on what gets capitalized...   Thank you @somascope for finding all the inconsistencies!
