### ISSUE TITLE
Change Colors on Pricing Page

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#148]
On the pricing page (and I did a customer walk through), the Team box is the most attractive thing to read and draws your eyes.  We'd like to fix this imbalance for launch.

The quickest fix might be to make the Team background also "White".  ..   And in the image of the people making the two white background people blue?  

Adam and I are open to another solution, but this seems like an easy fix for now.

**Comment by whosdustin** [comment]
Updated this to the white background and blue avatars.
