### ISSUE TITLE
Mobile login not working on Chrome

### ISSUE THREAD

**Issue by atomjar** [Code-Pop/vue-mastery#149]
When using Google Chrome on an iPhone 6S, when I am in the sign up model, I am not always able to tap and focus where I want to. Sometimes the blue blinking cursor will show up in an odd place (not in the 

Video of me demonstrating that is here:
https://www.dropbox.com/s/rjq8f7l5iyt3pao/IMG_3338.mov?dl=0

**Comment by Gregg** [comment]
Dustin could you please try to reproduce.  And see if there's any CSS tweaks you can make to have this less likely to happen.  OR try making the input fields different?

**Comment by Gregg** [comment]
Going to put this off until we have more users complaining.
