### ISSUE TITLE
add the link for support team in my subscriptions modal under user's dashboard section

### ISSUE THREAD

**Issue by rvamsikrishna** [Code-Pop/vue-mastery#152]
It would be better to display the  words "Support team" as link to the contact us page instead of plain text at the bottom of **My subscriptions** model under user's dashboard section.

![vue mastery](https://user-images.githubusercontent.com/31307345/39468107-08e7f228-4d4f-11e8-8295-bd5405e70abd.png)

**Comment by Gregg** [comment]
Doesn't look like Chargebee allows a link down here, so I changed to "Questions?  Please email team@vuemastery.com"  Hope that's okay, and thanks for the issue.  =)
