### ISSUE TITLE
Some videos not playing due to privacy settings

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#153]
While in the Intro course, I jumped ahead to L9, Communicating Events, and then used the lesson list to jump to L8, Components.

Maybe it has to do with your staging environment, but I was presented with no video that played, and instead saw a message (Vimeo, I think) saying: "Sorry Because of its privacy settings, this video cannot be played here."

![video-cannot-be-played](https://user-images.githubusercontent.com/8138678/39478318-b69eba0a-4d27-11e8-87af-465bb32cdc4c.png)

**Comment by Gregg** [comment]
Thanks for the heads up, I've made sure all videos can be watched on staging =)
