### ISSUE TITLE
VueConf videos not appearing

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#157]
Firebase storage error when viewing VueConf videos on https://vue-mastery-staging.firebaseapp.com/.

![vueconf-videos-not-appearing](https://user-images.githubusercontent.com/8138678/39479413-cf7d7d7e-4d2a-11e8-9e36-df9016d4dabd.png)

**Comment by Gregg** [comment]
This is okay for staging for now, we don't have all the same media on staging that we do for production.
