### ISSUE TITLE
Sign Up window's "accept" checkbox label not clickable

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#158]
When singing up, clicking the label next to the checkbox for "I accept the terms and conditions" doesn't check the box. Clicking or double-clicking the label text only selects the text, and ideally would check/uncheck the box.

I think the input element in the HTML needs to include: id="terms"

![signup-label-click](https://user-images.githubusercontent.com/8138678/39479990-843bf082-4d2c-11e8-8e57-cabf43d56ed6.png)

**Comment by pieer** [comment]
Good catch somascope. It's fixed now
