### ISSUE TITLE
Text edits on Advanced Component's Intro lesson

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#159]
In the lesson's text under "This course is:", consider hyphenating "hard to learn" so that it is "hard-to-learn". I saw that this also occurs under "What makes this course better than others?". One rule for hyphenating is: Generally, hyphenate two or more words when they come before a noun they modify and act as a single idea.

The sentence "I hope you chose to join me." sounds a little off. In the video, Greg says, "I hope you decide to join me...". Suggestions: Go with the same text per the video, or change the current "chose" (past tense) to "choose (present tense).

**Comment by Gregg** [comment]
Thanks! I've made these changes.
