### ISSUE TITLE
Congratulations window, Twitter share

### ISSUE THREAD

**Issue by ChaseWGregory** [Code-Pop/vue-mastery#164]
When completing the Intro Course, hovering over the Share to Twitter, I receive a cursor icon instead of an arrow or a finger to click.

<img width="1280" alt="screen shot 2018-05-08 at 11 31 44 pm" src="https://user-images.githubusercontent.com/35742533/39794447-67776ade-5318-11e8-899b-be372e3b9cb1.png">

**Comment by whosdustin** [comment]
This has been fixed.
