### ISSUE TITLE
Add Google Analytics tag for conversions

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#181]
When a user signs up for a monthly account please call this code:  Yeah we copied it from your user signup code.

```
  Vue.prototype.$trackMonthly = function(){
    ga('send', 'event', 'User', 'Monthly Subscription')
  }
```

When a user signs up for an annual account
```
  Vue.prototype.$trackAnnual = function(){
    ga('send', 'event', 'User', 'Annual Subscription')
  }
```

I think this ga syntax is correct, you'll want to verify there are no errors triggered.

**Comment by pieer** [comment]
Done
