### ISSUE TITLE
Adding a conference selection page

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#183]
Soon we'll have videos from other conferences pop up on Vue Mastery.  The top nav will change to "Conferences".. and when clicked the user will be brought to a page where:

Primary focus will be a list of conferences where we have video pages.   You are asked to select a conference to view those conference videos.  
   Text: "VueConf US 2018"   "New Orleans, LA - USA".   
    "14 session talks and 17 lightning talks"
    Button text: Watch Now

I just remembered that we created a VueConf badge, didn't we?  Given that.. I'm wondering if the page should resemble the courses page, and even have similar functionality.   
![course listing vue mastery](https://user-images.githubusercontent.com/2618/44488799-afe8b900-a627-11e8-92a5-a5e6db8b4512.jpg)

Secondary focus (on the sidebar) will be upcoming conferences.
Title: Upcoming Conferences

Vue.JS London 
September 2018
"Notify Me" when videos are up (this should likely be a button and work just like other notify me buttons around the site) 
Visit Conference

Notify me should be the call to action, while visit conference should be a smaller link that goes to the actual conference.  Also we could include a conference image, or not.

Connect.Tech 
October 2018

VueConf Toronto
November 2018

Are the other conferences and text.

**Comment by pieer** [comment]
This as been implemented
