### ISSUE TITLE
Cannot convert undefined or null to object     at Function.keys 

### ISSUE THREAD

**Issue by SuperLance** [Code-Pop/vue-mastery#184]
I cannot setup your project by your guide.
I created firebase.js and serviceAccountKey.json

I am getting this issue "Cannot convert undefined or null to object
    at Function.keys " when I run command "npm run dev"

Looking forward to hearing back.
Thanks.

**Comment by SuperLance** [comment]
![image](https://user-images.githubusercontent.com/18443121/46909998-920b4680-cf3c-11e8-98ef-03b16152a3ff.png)

**Comment by pieer** [comment]
Sorry for security reason, we don't provide the keys to access our database, email service or payment system.
For that reason, the solution can't be started.
May I ask the purpose of your interest for this website?
