### ISSUE TITLE
Add Subscriber Lists w/ Unsubscribe

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#185]
## New User Rules

When a new user joins our website (free) please ensure they join the following subscriber groups in mailerlite:

_Why this is important is because when they unsubscribe we ask if they want to leave the above groups, and they may only opt out of one of them instead of all_

- [x] VueMastery.com New Users (I think they already do this) (9028842)
- [x] Biweekly Newsletter (10930366)
- [x] Subscription Discounts and Promotions (10930360)
- [x] New Free Content Announcements (10930356)

## Paid Subscriber Rules

When a new paid subscriber joins, please ensure they join the following subscriber groups.  We might be able to do the separation between Monthly/Annual/Gift by using a new field in mailerlite and then using Segmentation.  Lemme know what you think the better solutions is.  For now I created subscriber groups.

_Why this is important is because we need to be upselling people who have monthly & gift subscriptions to annual subscriptions, and we want to create a drip campaign for this eventually_

- [x] Vue Mastery Subscribers (9620086)
- [x] Active Monthly Subscribers (if they have a monthly subscription) (10930362)
- [x] Active Annual Subscribers (if they have an annual subscription) (10930364)
- [x] Active Gift Subscription (10930392)

## Additional Tasks

- [x] Ensure that if someone cancels their account or their subscription status moves to cancelled (because of delinquent payment), they are removed from the above paid subscriber mailing lists.
- [x] Ensure that if someone goes from Monthly/Annual/Gift to another type of Subscription (Monthly/Annual/Gift) they are properly moved from group to group.

**Comment by pieer** [comment]
All the new rules are now implemented
