### ISSUE TITLE
Prepare for Free Weekend

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#187]
I did some work on this new Free Weekend branch:
https://github.com/Code-Pop/vue-mastery/tree/free-weekend

Take a look by starting up the dev server and going to http://localhost:3000/free-weekend

You'll get the gist.  I think I have it all setup properly, with requiring an account before it redirects to http://localhost:3000/thank-you-free-weekend

Take a look at that page too, to ensure I did the social sharing properly.

What I need help with, is if a user makes it to "http://localhost:3000/thank-you-free-weekend" I need them to get added to a mailing list "Free Weekend 2019" which I just added in Mailerlite, so I can properly email them when Free Weekend is in-action.

Thank you.

**Comment by pieer** [comment]
Done here:

**Comment by pieer** [comment]
Done here: https://github.com/Code-Pop/vue-mastery/commit/c77861dd13a063492f64188c3281405a9204d087
