### ISSUE TITLE
Create search prototype

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#188]
Using a service like Elastic Search, we want to push our content into the search engine using a local task, which will push each **published**:

Lesson
- Title
- Course Title
- Author
- Link to lesson
- Body content
- Image
- Duration
- Is lesson for paid subscribers only (true/false)

Conference Talk
- Title
- Conference Name
- Author
- Link to talk
- Body content
- Image
- Duration

And it will send this info into the search database.  

Then when someone searches for "conditionally display", here's is an example of what would pop up:

![vuemastery com_ conditionally display - google search](https://user-images.githubusercontent.com/2618/53193508-21a5bd80-35df-11e9-9677-3dddf6acd7d8.jpg)

Notice "(title) - (course title)", which in the case of conferences would be "(title) - (conference title)".  Notice the author and duration, and the bolded text that matches in the body.

First iteration I'd like you to create a prototype (separate from the website) that nails down this functionality before we try to bring it into the webpage.

If the lesson is only for paid subscribers, and the user is not a subscriber, it should probably display a "lock" icon at the end of the title, letting them know it's for paid members only.

**Comment by pieer** [comment]
Prototype done using our own server.

**Comment by pieer** [comment]
Need to find out if the output from elastic search can be filtering the body content and the video content
