### ISSUE TITLE
Github Login with Existing Account

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#189]
If user attempts to login with Github and they already have an account using another login method, they won't be logged in.  This console error isn't caught and isn't communicated to them.

![screenshot 2019-02-22 at 19 11 04](https://user-images.githubusercontent.com/2618/53271897-c4cd0480-36bd-11e9-9fa6-6abece06dd33.png)

**Comment by EbrahimKaram** [comment]
Hey So I made an account with Github on the platform and I can't seem to login in back again using GitHub

I'm a Windows 10 PC using Brave
