### ISSUE TITLE
Lesson 10: Forms has wrong video

### ISSUE THREAD

**Issue by terolblade** [Code-Pop/vue-mastery#221]
Hi!
it seems than Lesson 10: Forms has wrong video and no description 

https://www.vuemastery.com/courses/intro-to-vue-js/forms

Please check

![image](https://user-images.githubusercontent.com/3078649/61408466-c1dee480-a8e8-11e9-9200-6d7be7c2d078.png)

**Comment by bencodezen** [comment]
Hey @terolblade! Thanks for reporting this. I just checked and it looks like the correct video is up now. If you see otherwise, please don't hesitate to open another issue!
