### ISSUE TITLE
Dashboard link is covered by logo on mobile devices

### ISSUE THREAD

**Issue by bencodezen** [Code-Pop/vue-mastery#227]
# Problem

"Dashboard" is not accessible because it is covered by the logo on mobile screens.

![image](https://user-images.githubusercontent.com/4836334/68954800-bdd9ab00-0792-11ea-9ba6-9246299de7d5.png)

# Solution

Most likely a CSS issue.

**Comment by pieer** [comment]
This is fixed in production now
