### ISSUE TITLE
download cheat sheet buttons do not work

### ISSUE THREAD

**Issue by vesper8** [Code-Pop/vue-mastery#228]
The "Download it free" buttons located
https://www.vuemastery.com/vue-cheat-sheet/
https://www.vuemastery.com/nuxt-cheat-sheet/
and
https://www.vuemastery.com/vue-3-cheat-sheet/

Simply do not work, nothing happens when I click them, they are unclickable. This is whether I am signed in to my free account or not

Thankfully I was able to get them from this repository

**Comment by bencodezen** [comment]
Thank you so much for reporting this @vesper8. I've identified the issue and will get a fix for this pronto!

**Comment by pieer** [comment]
All fixed. Thanks for the reports guys!
