### ISSUE TITLE
Video display issues in Lesson pages

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#23]
Win 7/FF 58. The video that appears at the top of the lesson page is sized like a thumbnail; it’s not scaling to fit in its container for some reason. Also, when the browser is narrowed to show the mobile menu breakpoint (~1200 px), the video disappears and all I see is the lesson’s first H1 element.

**Comment by whosdustin** [comment]
Adding screenshot. This issue spans across FF.

![image](https://user-images.githubusercontent.com/940208/37270703-62a9c08a-2602-11e8-8299-62606acb1e2d.png)
