### ISSUE TITLE
Implement Free Week Items

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#234]
I pushed some code to master so people can start signing up for Free Week tomorrow.  However, I need your help finishing it up:

First priority:
- [x] Fix big white block on the free week and free weekend page (for now there are two static pages both pointing to FreeWeekendMain.vue), which I think makes sense to me. 
- [x] When people click to register for free week, please ensure they get added to this mailing list: https://app.mailerlite.com/subscribers/view/102481298
- [x] Add the social image which is hopefully posted to the marketing page.
- [x] Test it out locally.  Yes, this is all that should be changed for now.  I might add a banner later this week, but this is all I think we need for now.
- [x] Deploy
- [x] Clone Vuejs.org and implement free weekend banner, with April 13 - April 20 dates, and linking to https://www.vuemastery.com/free-week  . I'll take a look in my morning, and then do the pull request.

Second priority:
- [x] Create a branch that has all the code ready for free week, so you can deploy it at 12 AM ET your Monday April 13th.

**Comment by pieer** [comment]
Implemented
