### ISSUE TITLE
Mobile view, footer links not working

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#26]
I noticed this on my Galaxy S7 first, and then on desktop (Win 7/FF 58/Chrome 65) with a browser narrowed to show the mobile layout. In these scenarios, the links seem to be non-existent. Pressing on them does nothing, and on desktop there is no link destination showing in the lower-left of the window.

**Comment by pieer** [comment]
This might be fixed, I can't reproduce
