### ISSUE TITLE
Ensure Google Analytics is Setup Properly

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#3]
Google Analytics tag for VueMastery.com is `UA-90157003-2`.  I just gave you access.

Implement user_id tracking.  If the user is logged in, you should call this once.  Could be when they first visit, or when they login / signup.

```this.$ga.set({ 'user_id', <user_id> })```

We need to properly track where people are signing up around the website.  When someone signs up the following event should be triggered:

```this.$ga.event('User', 'Created Account', '<location>', 1)```

The location should refer to the place where the user created an account: 

* Front-page cheat sheet download
* Top-right navigation
* Course page cheat sheet download
* Course page notify me
* Lesson page download button
* Lesson page checkbox
* Lesson page locked video

Under google analytics (if we're not including it already) we need to include the Vimeo tracking code, that gives us google events from the Vimeo players, so we can track which videos people are playing through.

```<script type="text/javascript" defer="defer" src="https://extend.vimeocdn.com/ga/72160148.js"></script>```

**Comment by pieer** [comment]
I've implemented the analytics and test to see if the event are going, but we need to check they are recorded correctly

**Comment by Gregg** [comment]
Looks great to me.
