### ISSUE TITLE
Change background color to Course list on homepage

### ISSUE THREAD

**Issue by whosdustin** [Code-Pop/vue-mastery#31]
If you look at the above screenshot, the Free Lessons block seems nicely blocked in where as the Courses block seem to be dangling a bit. In the screenshot below I have added a slight grey background color to see what it would look like, to me personally it gives it a bit more visual structure 🙂 

![image](https://user-images.githubusercontent.com/940208/37276362-117d23ac-2614-11e8-9c2f-99ea7b915b7f.png)

**Comment by Gregg** [comment]
That looks nice to me...  Please do it @whosdustin
