### ISSUE TITLE
Add Icons to lesson sidebar cards

### ISSUE THREAD

**Issue by whosdustin** [Code-Pop/vue-mastery#32]
It was suggested to add some contrast within the cards along the sidebar of the lessons.

![image](https://user-images.githubusercontent.com/940208/37276695-1314b9b8-2615-11e8-95b7-0c16d827838a.png)

**Comment by Gregg** [comment]
Yes, these need something that makes it more obvious what they are.    Code Challenges.. etc.  Any ideas?

**Comment by whosdustin** [comment]
The suggestion was adding icons next to the titles of these cards. I like the idea and will implement what makes most sense.
