### ISSUE TITLE
Header Capitalization Items

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#37]
For what it's worth, there are also heading consistency issues in the text versions of the lessons (which I didn't capture here). See what you guys think and discuss if you want to be consistent with sentence case (just the first word capitalized) or title case (which seems to be more often used). I've found it helpful to use this online tool when using title case when you're not sure which words to capitalize: https://capitalizemytitle.com/

Here are items to consider updating.

 - "Welcome back!" (when pressing Login button), change to "Welcome Back!"
 - "Signup" button in the "Welcome back!" modal, change to "Sign Up". It is already "Sign Up" in the main nav bar.
 - "Sign up to unlock free content" (when pressing Unlock content button), change to "Sign up to Unlock Free Content"
 - "This lesson is locked." message, change to "This Lesson Is Locked."
 - "Unlock content" button, change to "Unlock Content"
 - "Listen to the podcast" button, change to "Listen to the Podcast"

Consider the all-caps button labels and changing them to title case. This is totally up to you, depends on consistency versus marketing "loudnesS" of button labels: "START LEARNING NOW" and "DOWNLOAD IT FREE" on the on About page.

**Comment by pieer** [comment]
I've updated the titles and buttons. I just leave the post open so everyone involved in editing the content can read it.

**Comment by somascope** [comment]
Nice idea. I didn't know how far to go, but it's something that I notice on various sites and always get a little bit more aware of this kind of issue the more I see it.
