### ISSUE TITLE
Change prompt at end of video if not logged in

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#41]
I'd like to change the prompt when they get to the end of the video if they are not signed in, to encourage them to save their progress.   Rather than a countdown:

![screenshot 2018-03-12 18 45 53](https://user-images.githubusercontent.com/2618/37318205-7f5713da-2626-11e8-9d90-92f1d005e0cf.jpg)

If they click to Save their Progress then the signup model should pop up, and once signed up or logged in please verify that the checkbox is checked for the video they just watched, and they are delivered to the next video.  =)

**Comment by pieer** [comment]
I've done everything except that the user is not redirected after he click on "Save my progress".
There is two reasons for that:
- From UX point of view, clicking on go to next lesson should redirect, saving my progress is a different action and I don't think it should redirect. Once the user is logged in, it should stay on the same page but the lesson is mark as completed however.
- It's actually a bit tricky to implement: I need to path
