### ISSUE TITLE
Incomplete course showing up under Completed

### ISSUE THREAD

**Issue by atomjar** [Code-Pop/vue-mastery#42]
Since I've watched 4/4 videos of the Intro course, that course is showing up in the Completed section of my dashboard. However, that course should still be up in the In Progress section. We need a course to be able to be set as completable or not. That way, a course will only show up in the Completed section when a user has watched all of the lessons in that course AND that course is completable: true.

**Comment by pieer** [comment]
That's done.
What do you think of this message:
![image](https://user-images.githubusercontent.com/312402/37406521-a1f926d6-2797-11e8-8b71-54af616ec744.png)

**Comment by pieer** [comment]
Chnage text to be less gray and no nold
Change the button to notify me.
