### ISSUE TITLE
Share modal window is 100% browser height

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#46]
The Share modal window spans the entire height of the browser, as if it was 100vh.

**Comment by Gregg** [comment]
Can you post a screenshot?  Unsure what you mean.

**Comment by pieer** [comment]
![image](https://user-images.githubusercontent.com/312402/37417134-ca8429e4-27af-11e8-928a-32f227ee1048.png)

**Comment by somascope** [comment]
Thanks Pierre. The bottom will extend down to the bottom of your browser, even on taller views/monitors.
