### ISSUE TITLE
Fix Contact form and Improve Submit UI 

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#49]
I submitted the contact form while logged out and no email was sent to team@vuemastery.com.  

Also, when the contact form is submit, the UI could be improved.  Please remove the text in the fields if the send is successful, and change the state / text of the submit button to make it seem pressed.  Maybe change the text to "Thank You"?

**Comment by pieer** [comment]
I've updated the UI.
Concerning the email, I need to configure a gmail address for the server.
Which address and password should I use?
