### ISSUE TITLE
Give learners place to go at end of lesson.  

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#5]
When learners finish a lesson and have a question, we need to direct them somewhere.  I think we've decided to direct them to our facebook group: https://www.facebook.com/groups/152305585468331/

Before we need to put something on each lesson page in this interest.  "If you'd like to discuss this lesson please join our **facebook group**.  If you have any feedback feel free to **get in touch**."  Get in touch should link the contact form.

Unsure of the placement.  It could be at the end of each lesson, but then what about people who are just watching the videos?  They may never scroll down that far.

**Comment by whosdustin** [comment]
We had something designed for this in the beginning (Join our channel). We opted out of this feature for lack of channel or something along those lines. We could just add the buttons below the coding challenges in the sidebar. Similarly shown in the picture below.

![image](https://user-images.githubusercontent.com/940208/37141321-338d6252-22e7-11e8-96e7-2dfac0e6f0b7.png)

**Comment by Gregg** [comment]
How about two buttons:

Discuss in our Facebook Group

Send us Feedback 

?

**Comment by max-devjs** [comment]
Sending Feedback... and those who do **not** use Facebook?

**Comment by max-devjs** [comment]
Would be the use of Github issues pertinent...?

**Comment by Gregg** [comment]
I know not everyone uses facebook, but it seems like a good temporary solution, and a good way to build our facebook social presence.  I'd like to see two buttons.  Dustin can you do this?

Discuss in our Facebook Group
Send us Feedback

**Comment by whosdustin** [comment]
Will do. @Gregg does Send Us Feedback point to contact page?
