### ISSUE TITLE
Mockup New Lesson Resource & Coding Challenge boxes

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#53]
This is my normal browser resolution.  It just doesn't look great.

![image](https://user-images.githubusercontent.com/2618/37424197-50212c60-2796-11e8-9b3b-f4326aa10e47.png)

The icons helped the Lesson Resource and Coding Challenge boxes, but these boxes just don't look pretty to look at.  Let's give them some design love post-launch?

**Comment by whosdustin** [comment]
During my styles refactor there will be some major tweaks to everything that will make all these micro-interactions to work and feel better. Might need to have a UI milestone/project for these pieces

**Comment by whosdustin** [comment]
I want to take a note that in the videos we reference the **Challenge** is linked to the "Code Playground" and on the page, the heading for the aforementioned playground is called "Coding Challenges". Also, the **Challenge** text is at the bottom of the content but the card containing the links are in the sidebar.
![untitled 001](https://user-images.githubusercontent.com/940208/40873146-e0eeb8b6-6652-11e8-84ae-6ac6ebe3ba63.jpeg)

**Comment by pieer** [comment]
Is this still relevant?
