### ISSUE TITLE
Adjust the time of the Vimeo player left & right arrow key skipping

### ISSUE THREAD

**Issue by somascope** [Code-Pop/vue-mastery#61]
I've gotten so used to YouTube's skip feature with the left & right arrow keys where the video skips backward/forward by 5 seconds. Currently the Vimeo default is maybe 1 second, which isn't very useful when you want to quickly review the last sentence that you heard. Consider modifying this to skip by 5 or 10 seconds.

**Comment by somascope** [comment]
Apparently, my idea isn't possible... I contacted Vimeo and got this:

"Sorry, it's not currently possible to change the scrub time that the keyboard controls. We appreciate getting feedback from the community about how we can improve our service. I'm making note of your suggestion, and I will share it with our product team as a feature request."

So unless the team was feeling ambitious and wanted to code your own video player that played Vimeo-hosted content, this issue could be closed.

**Comment by pieer** [comment]
Thanks somascope, we don't want to implement a new video player atm.
