### ISSUE TITLE
Save Playback Rate Between Vimeo Videos

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#75]
At the moment if you set the playback rate to 1.5 or 2.0 it does not get saved between videos.  Please add the JavaScript code so this gets saved.

I contacted Vimeo support to figure out the best way to do this.  You need to use their player API.

You'll need to call [getPlaybackRate](https://github.com/vimeo/player.js#getplaybackrate-promisenumber-error) on the Vimeo API, and then [setPlayBackRate](https://github.com/vimeo/player.js#setplaybackrateplaybackrate-number-promisenumber-rangeerrorerror) when a video is loaded.

I went looking through laracasts code to see how they did this, if you want a hint: https://gist.github.com/Gregg/002db273584130c421a009a5e052167d

Looks like they call setInterval, and just check to see if the speed is changed.  I wonder if that's the best way.

**Comment by pieer** [comment]
Fix in staging
