### ISSUE TITLE
Add fade in instead of navigation switch on login

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#80]
When I'm logged in and initially go to www.VueMastery.com the navigation and top right links switch from login / signup to sign out / picture when it recognizes I'm logged in.  Also "Dashboard" appears.

Please add an animation for both these events.   The top right can be blank until we recognize the user is or isn't logged in .. then these elements can fade in.   

Dashboard should be able to fade in ... and maybe the other navigation links animate over.

Pierre, if you are unsure how to do this, I have friends who can help =)

**Comment by pieer** [comment]
Great feedback Gregg, exactly the one I like to implement.
I know really well how to implement this however if your friend is Sarah Drasner, I would love be in contact :)
