### ISSUE TITLE
Build Thank You pages for payment completion

### ISSUE THREAD

**Issue by whosdustin** [Code-Pop/vue-mastery#90]
You now have access to all of our paid content.

`<call to action: Start Learning>`

We will be sending $X of your monthly payment to the Vue.js project.

`<call to action: [View the Vue.js Roadmap](https://github.com/vuejs/roadmap)>` [https://github.com/vuejs/roadmap](https://github.com/vuejs/roadmap)

Your subscription will automatically renew on <subscription.next_billing_at>

If you ever want to modify, suspend, or cancel your subscription, just head over to your profile page by clicking the image in the top right of your screen, and hitting the button that looks like: `<call to action: My Subscription>`

If you have any feedback for us, need some support, or want to request any content, we’d love to hear from you. You can use the contact us form or just email `team@vuemastery.com`.

**Comment by Gregg** [comment]
Now that we're further along it's more clear what should be on this page.  Please see:

https://paper.dropbox.com/doc/Thank-You-Yyqzurtvg88SH1JkyW7cI?_tk=share_copylink

**Comment by whosdustin** [comment]
This has been completed and will close once the branch is merged with master.

**Comment by Gregg** [comment]
Closing out.  Looks great.
