### ISSUE TITLE
If they clicked on “Contact Us”  they are shown a contact form modal

### ISSUE THREAD

**Issue by pieer** [Code-Pop/vue-mastery#94]
This should have the following fields, and send an email to team@vuemastery.com

Your name?

Email address? (this should be pre-populated from their account info)

Company website?

Phone Number?

How many accounts do you think you’ll need?

Once they submit the form it should say..   “Thank you for your interest, we should be in touch within a day (unless it’s a weekend).”  Let’s make sure this is bigger and stays on the screen longer than our current notification window thing.

**Comment by Gregg** [comment]
Tried this form on staging, got:

![image](https://user-images.githubusercontent.com/2618/39382542-d1972ece-4a33-11e8-9c46-40d1b47a4bdb.png)

**Comment by pieer** [comment]
That's fixed now
