### ISSUE TITLE
Add two thank you pages

### ISSUE THREAD

**Issue by pieer** [Code-Pop/vue-mastery#95]
In Google analytics I’ve created two goals to track how many people convert.  This is just to track the behavior of subscribers.   Actual revenue will be tracked through chargebee.  

If they created a Monthly account they should be delivered to the following URL: vuemastery.com/thank-you-monthly
If they created a Annual account they should be delivered to the following URL: vuemastery.com/thank-you-annual

If you change these URLs, be sure to update the goals on Google Analytics.

**Comment by Gregg** [comment]
Works great
