### ISSUE TITLE
Adding new subscriber to the mailing list

### ISSUE THREAD

**Issue by pieer** [Code-Pop/vue-mastery#96]
When someone’s subscription becomes active (likely through the webhook), we should add them to a group in Mailerlite for just Subscribers.  This way I can prepare a welcome email for them in Mailerlite to automatically send out.  This email will say:

- Thank you for subscribing.  Over the next year we’ll be building out a huge library of educational content for Vue.js.  
- Links to paid courses, in this case just Advanced Components.
- If you ever want to modify, suspend, or cancel your subscription, just head over to your profile page by clicking the image in the top right of your screen, and hitting the button that looks like:  <call to action: My Subscription>
- If you have any feedback or want to let us know what content you’re most looking forward to, please do not hesitate to respond to this email and we’ll be in touch.

**Comment by Gregg** [comment]
Created this email..
